import Link from "next/link";
import Layout from "@/components/layout/Layout";

export const metadata = {
  title: "Communiqués de presse | ATR",
  description: "Déclarations et annonces officielles de l'Association Tunisienne des Routes.",
  openGraph: { title: "Communiqués de presse | ATR", description: "Salle de presse officielle de l'ATR.", type: "website" },
};

const releases = [{
  reference: "Communiqué n°01-2025",
  date: "6 août 2025",
  subject: "Audience officielle consacrée au nouveau bureau exécutif de l'Association Tunisienne des Routes",
  summary: "Le nouveau bureau exécutif de l'ATR a été reçu par le ministre de l'Équipement et de l'Habitat, en présence de représentants de PIARC.",
  href: "/communiques/01-2025",
}];

const styles = `
  .atr-press-page{background:#f5f7fa;color:#17233d;padding-bottom:80px}.atr-press-intro{padding:78px 0 48px;background:#fff}.atr-press-intro h1{color:#102b54;font-size:44px;line-height:1.15;margin:8px 0 14px}.atr-press-intro p{max-width:720px;color:#536175;font-size:18px;line-height:1.7}.atr-press-intro .section_heading_title_small,.atr-press-contact .section_heading_title_small{color:#C07B1B;font-weight:800;letter-spacing:.08em;text-transform:uppercase}.atr-press-contact{margin:40px auto 0;padding:24px 28px;background:#eef3f7;border-left:4px solid #C07B1B;border-radius:10px;max-width:1180px;display:flex;justify-content:space-between;gap:25px;align-items:center}.atr-press-contact h2{color:#102b54;font-size:21px;margin:5px 0}.atr-press-contact p{color:#536175;margin:0;line-height:1.6}.atr-press-contact a{color:#174f86;font-weight:800;text-decoration:none}.atr-press-list{padding:65px 0}.atr-press-list h2{color:#102b54;font-size:32px;margin:8px 0 28px}.atr-press-entry{display:grid;grid-template-columns:150px 1fr auto;gap:25px;align-items:start;padding:25px 0;border-top:1px solid #d5dee8}.atr-press-ref{color:#68778c;font-family:monospace;font-size:13px}.atr-press-date{display:block;margin-top:8px;color:#C07B1B;font-family:inherit;font-weight:800}.atr-press-entry h3{color:#102b54;font-size:22px;line-height:1.35;margin:0 0 9px}.atr-press-entry p{color:#536175;line-height:1.65;margin:0;max-width:680px}.atr-press-actions{display:flex;flex-direction:column;gap:10px;min-width:150px}.atr-press-actions a{padding:10px 13px;border-radius:6px;text-align:center;text-decoration:none;font-size:13px;font-weight:800}.atr-press-read{border:1px solid #1B5299;color:#174f86}.atr-press-print{background:#1B5299;color:#fff}.atr-press-crosslink{padding:38px 0;background:#102b54}.atr-press-crosslink h2{color:#fff;font-size:27px;margin:0 0 9px}.atr-press-crosslink p{color:#d5dfeb;line-height:1.7;margin:0 0 16px}.atr-press-crosslink a{color:#F69F1A;font-weight:800;text-decoration:none;margin-right:22px}@media(max-width:767px){.atr-press-intro{padding:52px 0 35px}.atr-press-intro h1{font-size:34px}.atr-press-contact{display:block;margin:25px 15px 0}.atr-press-entry{grid-template-columns:1fr;gap:12px}.atr-press-actions{flex-direction:row;flex-wrap:wrap}.atr-press-actions a{flex:1}.atr-press-list{padding:48px 0}.atr-press-crosslink a{display:block;margin:9px 0}}
`;

export default function CommuniquesPage() {
  return <Layout headerStyle={1} footerStyle={1} breadcrumbTitle="Communiqués de presse"><main className="atr-press-page"><style dangerouslySetInnerHTML={{ __html: styles }} /><section className="atr-press-intro"><div className="auto-container"><p className="section_heading_title_small">Salle de presse ATR</p><h1>Communiqués de presse</h1><p>Déclarations et annonces officielles de l'Association Tunisienne des Routes. Cette rubrique démarre avec un communiqué documenté ; les prochains documents seront ajoutés après validation institutionnelle.</p></div></section><section className="atr-press-contact"><div><p className="section_heading_title_small">Contact presse</p><h2>Association Tunisienne des Routes</h2><p>Pour une demande média : <a href="mailto:contact@atr.org.tn">contact@atr.org.tn</a> · <a href="tel:+21671234567">+216 71 234 567</a></p></div><span>Réponse habituelle sous 48h ouvrées</span></section><section className="atr-press-list"><div className="auto-container"><p className="section_heading_title_small">Archives officielles</p><h2>Communiqués disponibles</h2>{releases.map((release) => <article className="atr-press-entry" key={release.reference}><div className="atr-press-ref">{release.reference}<time className="atr-press-date">{release.date}</time></div><div><h3>{release.subject}</h3><p>{release.summary}</p></div><div className="atr-press-actions"><Link href={release.href} className="atr-press-read">Lire en ligne</Link><Link href={`${release.href}?print=1`} className="atr-press-print">Version imprimable</Link></div></article>)}</div></section><section className="atr-press-crosslink"><div className="auto-container"><h2>Vous cherchez un autre contenu ?</h2><p>Les annonces courtes sont dans Actualités ; les comptes-rendus détaillés et revues de presse sont dans Publications.</p><Link href="/actualites">Voir les Actualités →</Link><Link href="/publications">Voir les Publications →</Link></div></section></main></Layout>;
}
