'use client'
import { useMemo, useState } from 'react';
import Link from 'next/link';
import Layout from '@/components/layout/Layout';

const categories = {
  all: { label: 'Tout', color: '#1B5299' },
  announcement: { label: 'Annonce', color: '#1B5299' },
  application: { label: 'Appel à candidature', color: '#C07B1B' },
  life: { label: "Vie de l'association", color: '#7A4E9A' },
  event: { label: 'Événement', color: '#2E8B57' },
};

const news = [
  { id: 1, category: 'announcement', date: '6 août 2025', title: 'Le nouveau bureau de l’ATR reçu par le ministre de l’Équipement', summary: 'Une audience officielle a réuni le nouveau bureau exécutif de l’ATR, le ministère et des représentants de PIARC.', href: '/publications/ministre-equipement-accueille-bureau-atr', linkLabel: 'Lire le compte-rendu' },
  { id: 2, category: 'event', date: '30 avril 2026', title: 'Rencontre ATR sur les enjeux HSS et la sécurité routière', summary: 'À la Cité des Sciences de Tunis, les échanges ont porté sur la responsabilité humaine et la sécurité des chantiers.', href: '/publications/securite-routiere-hss-chantiers', linkLabel: 'Lire la publication' },
  { id: 3, category: 'event', date: 'Décembre 2026', title: 'Le Séminaire international des Comités Techniques PIARC est annoncé à Tunis', summary: 'L’ATR et PIARC préparent un séminaire consacré aux pratiques et aux enjeux contemporains de la route.', href: '/events/seminaire-piarc-2026', linkLabel: 'Voir le séminaire' },
];

const styles = `
  .atr-news-page{background:#f5f7fa;color:#17233d;padding-bottom:80px}.atr-news-intro{padding:78px 0 52px;background:#fff}.atr-news-intro h1{color:#102b54;font-size:44px;line-height:1.15;margin:8px 0 14px}.atr-news-intro p{color:#536175;font-size:18px;line-height:1.7;max-width:720px}.atr-news-intro .section_heading_title_small,.atr-news-section .section_heading_title_small,.atr-news-crosslink .section_heading_title_small{color:#C07B1B;font-weight:800;letter-spacing:.08em;text-transform:uppercase}.atr-news-section{padding:70px 0 35px;border-top:1px solid rgba(192,123,27,.3)}.atr-news-filters{display:flex;gap:9px;flex-wrap:wrap;margin:24px 0 34px}.atr-news-filter{border:1px solid #cdd9e5;border-radius:999px;background:#fff;color:#174f86;padding:9px 14px;font:inherit;font-size:13px;font-weight:800;cursor:pointer}.atr-news-filter.active{background:#102b54;border-color:#102b54;color:#fff}.atr-news-timeline{position:relative;max-width:850px;padding-left:145px}.atr-news-timeline:before{content:'';position:absolute;left:114px;top:0;bottom:0;width:2px;background:#e2b56d}.atr-news-item{position:relative;padding:0 0 35px}.atr-news-item:before{content:'';position:absolute;left:-37px;top:4px;width:12px;height:12px;border:3px solid #fff;border-radius:50%;background:#C07B1B;box-shadow:0 0 0 2px #C07B1B}.atr-news-date{position:absolute;left:-145px;top:0;width:100px;color:#68778c;font-size:13px;font-weight:800;line-height:1.4;text-align:right}.atr-news-entry{background:#fff;border:1px solid #dfe6ee;border-radius:14px;padding:22px 25px;box-shadow:0 8px 22px rgba(16,43,84,.06);transition:transform .2s,box-shadow .2s}.atr-news-entry:hover{transform:translateY(-3px);box-shadow:0 15px 30px rgba(16,43,84,.12)}.atr-news-category{display:inline-block;padding:5px 9px;border-radius:999px;color:#fff;font-size:11px;font-weight:800;text-transform:uppercase;letter-spacing:.05em}.atr-news-entry h2{color:#102b54;font-size:22px;line-height:1.3;margin:13px 0 8px}.atr-news-entry p{color:#536175;line-height:1.65;margin:0}.atr-news-entry a{display:inline-block;margin-top:14px;color:#174f86;font-size:14px;font-weight:800;text-decoration:none}.atr-news-empty{padding:25px;background:#fff;border:1px solid #dfe6ee;border-radius:12px;color:#536175}.atr-news-crosslink{margin-top:55px;padding:38px;background:#102b54;color:#fff;border-radius:14px}.atr-news-crosslink h2{color:#fff;font-size:27px;margin:8px 0 10px}.atr-news-crosslink p{color:#d5dfeb;line-height:1.7;margin:0 0 18px}.atr-news-crosslink a{display:inline-block;padding:12px 17px;border-radius:7px;background:#C07B1B;color:#fff;font-weight:800;text-decoration:none}@media(max-width:767px){.atr-news-intro{padding:52px 0 35px}.atr-news-intro h1{font-size:34px}.atr-news-section{padding:48px 0 25px}.atr-news-timeline{padding-left:28px}.atr-news-timeline:before{left:5px}.atr-news-item:before{left:-26px}.atr-news-date{position:static;width:auto;text-align:left;margin-bottom:9px}.atr-news-entry h2{font-size:20px}}
`;

export default function ActualitesPage() {
  const [activeCategory, setActiveCategory] = useState('all');
  const visibleNews = useMemo(() => activeCategory === 'all' ? news : news.filter((item) => item.category === activeCategory), [activeCategory]);
  return <Layout headerStyle={1} footerStyle={1} breadcrumbTitle="Actualités"><main className="atr-news-page"><style dangerouslySetInnerHTML={{ __html: styles }} /><section className="atr-news-intro"><div className="auto-container"><p className="section_heading_title_small">Vie de l'ATR</p><h1>Actualités</h1><p>Brèves et annonces de l’ATR, mises à jour régulièrement. Cette page suit la vie institutionnelle et les rendez-vous de l’association ; les comptes-rendus détaillés et revues de presse sont regroupés dans Publications.</p></div></section><section className="atr-news-section"><div className="auto-container"><p className="section_heading_title_small">Fil chronologique</p><h2>Les dernières nouvelles</h2><div className="atr-news-filters" role="tablist" aria-label="Filtrer les actualités">{Object.entries(categories).map(([key, category]) => <button key={key} className={`atr-news-filter ${activeCategory === key ? 'active' : ''}`} onClick={() => setActiveCategory(key)}>{category.label}</button>)}</div>{visibleNews.length ? <div className="atr-news-timeline">{visibleNews.map((item) => <article className="atr-news-item" key={item.id}><time className="atr-news-date">{item.date}</time><div className="atr-news-entry"><span className="atr-news-category" style={{ background: categories[item.category].color }}>{categories[item.category].label}</span><h2>{item.title}</h2><p>{item.summary}</p>{item.href && <Link href={item.href}>{item.linkLabel} <span aria-hidden="true">→</span></Link>}</div></article>)}</div> : <p className="atr-news-empty">Aucune actualité publiée dans cette catégorie pour le moment.</p>}<div className="atr-news-crosslink"><p className="section_heading_title_small">Pour aller plus loin</p><h2>Vous cherchez nos contenus détaillés ?</h2><p>Consultez les comptes-rendus de rencontres et les revues de presse vérifiés de l’ATR.</p><Link href="/publications">Consulter les Publications →</Link></div></div></section></main></Layout>;
}
